export const INCREASE_BASIC = "INCREASE_BASIC";
export const DECREASE_BASIC = "DECREASE_BASIC";
export const INCREASE_SENIOR = "INCREASE_SENIOR";
export const DECREASE_SENIOR = "DECREASE_SENIOR";
export const TICKET_TYPE = "TICKET_TYPE";
export const FORM_TICKET_BUY = "FORM_TICKET_BUY";
export const SELECT_TICKET_TYPE = "SELECT_TICKET_TYPE";
